---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cron-config-v1
  namespace: level9
data:
  CRON_HOST_URL: cron.level9.svc.cluster.local
  CRON_AUTH_TOKEN: e2c0b54a-baf0-4bd8-9cb1-e0151b16e83d
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-mail
  namespace: level9
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      backoffLimit: 1 # Retry 1 time if fail
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: cron
              image: workshopk8s/k8s-workshop-level9-cronjob:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: cron-config-v1
