---
apiVersion: v1
kind: Namespace
metadata:
  name: level8
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: level8
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: upload
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: upload
  namespace: level8
spec:
  rules:
    - host: upload.level8.localhost
      http:
        paths:
          - backend:
              serviceName: upload
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload-nginx
        image: workshopk8s/k8s-workshop-level8-upload-nginx
        ports:
        - containerPort: 80
      - name: upload-php
        image: workshopk8s/k8s-workshop-level8-upload-php
