---
apiVersion: v1
kind: Namespace
metadata:
  name: level1
---
apiVersion: v1
kind: Pod
metadata:
  name: broken-slackbot
  namespace: level1
spec:
  containers:
  - name: python-slackbot
    image: workshopk8s/k8s-workshop-level1-slackbot
    env:
    - name: "WORKSHOP_SLACK_TOKEN"
      value: "THIS IS AN INVALID VALUE"
    - name: "WORKSHOP_SLACK_CHANNEL"
      value: "THIS IS AN INVALID VALUE"
    - name: "WORKSHOP_YOUR_NAME"
      value: "THIS IS AN INVALID VALUE"
    - name: "ANSWER_TO_THE_ULTIMATE_QUESTION_OF_LIFE_THE_UNIVERSE_AND_EVERYTHING"
      value: "43"
