---
# From https://github.com/rancher/k3s/blob/master/docker-compose.yml
# Part of the awesome k3s project
# This file and k3s licensed under Apache2 :
# https://github.com/rancher/k3s/blob/master/LICENSE
#
version: '3'
services:
  server:
    image: rancher/k3s:v0.8.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s:z
    # This is just so that we get the kubeconfig file out
    - .output:/output:z
    - "./level1/.backstage/level1.yml:/var/lib/rancher/k3s/server/manifests/level1.yml:ro"
    - "./level2/.backstage/level2.yml:/var/lib/rancher/k3s/server/manifests/level2.yml:ro"
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.8.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
    ports:
      - "8090-8099:80"

volumes:
  k3s-server: {}
