---
apiVersion: v1
kind: Namespace
metadata:
  name: level2
---
apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: level2
spec:
  ports:
    - name: 'amqp'
      port: 5672
      targetPort: 5672
    - name: 'management'
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: level2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
      name: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management-alpine
        imagePullPolicy: Always
        name: rabbitmq
      restartPolicy: Always
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: producer
  namespace: level2
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: hugoshaka/k8s-workshop-level2-producer
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: level2
  labels:
    app: consumer
spec:
 containers:
 - name: worker
   image: hugoshaka/k8s-workshop-level2-worker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq
  namespace: level2
spec:
  rules:
    - host: rabbitmq.level2.localhost
      http:
        paths:
          - backend:
              serviceName: rabbitmq
              servicePort: 15672
