---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload-nginx
        image: workshopk8s/k8s-workshop-level8-upload-nginx
        volumeMounts:
            - name: upload-data
              mountPath: /home/docker/uploads
        ports:
        - containerPort: 80
      - name: upload-php
        image: workshopk8s/k8s-workshop-level8-upload-php
        volumeMounts:
          - name: upload-data
            mountPath: /home/docker/uploads
      volumes:
          - name: upload-data
            emptyDir: {}